services:
  - type: web
    name: omniroute
    env: image
    image:
      url: docker.io/diegosouzapw/omniroute:latest
    region: ohio
    plan: free
    envVars:
      - key: PORT
        value: "20128"
      - key: OMNIROUTE_MEMORY_MB
        value: "384"
